### PR TITLE
ci: More test cleanups

### PR DESCRIPTION
**Pull request by nirs**
- Use lima from brew
- Add apt-get update before install
- Use plain mode

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
> **Merging is blocked**
> Merging can be performed automatically with 1 approving review.

GitHub no longer recognizes me as a maintainer 😄

**Review by AkihiroSuda — DISMISSED** [review]

**Comment by nirs** [comment]
Rebase on master, ready for merge.

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
